Repository skyzh/canvas_grab, pull requests merged in 2020-04, with the labels that each got.

#61 [code] concurrent resolving module file
  main.py
Labels: enhancement

#63 Remove comments
  README.md
  README_zh-hans.md
  main.py
  version.py
Labels: enhancement

#64 make remove_empty_dir safer
  main.py
Labels: bug

#66 [code] warn users on wrong file size
  download_file.py
Labels: bug

#70 Not exit when fail
  download_file_ex.py
  main.py
Labels: enhancement

#76 add version message and illigal filename replacement
  main.py
  utils.py
Labels: bug, enhancement

#78 Ignore file with no size
  main.py
  version.py
Labels: bug
