Repository skyzh/canvas_grab, pull requests merged in 2020-03, with the labels that each got.

#21 fix some typo in README
  README.md
  README_zh-hans.md
Labels: documentation

#24 Update video-related documentation
  README.md
  README_zh-hans.md
  config.example.toml
  config.example.zh-hans.toml
Labels: documentation

#23 Fix pyinstaller onefile related issue
  download_file.py
  main.py
Labels: bug

#25 [code] fix download bar on windows
  download_file.py
Labels: bug

#26 add ffmpeg path config
  .gitignore
  README.md
  config.example.toml
  config.example.zh-hans.toml
  config.py
  main.py
  version.py
Labels: documentation, enhancement

#30 [doc] add warning for review license
  README.md
  README_zh-hans.md
  config.py
  main.py
Labels: documentation

#31 Fix resource does not exist
  main.py
  version.py
Labels: bug

#32 [doc] update readme for macos
  README.md
  README_zh-hans.md
Labels: documentation

#34 add support for module
  README.md
  README_zh-hans.md
  config.example.toml
  config.example.zh-hans.toml
  config.py
  main.py
  utils.py
  version.py
Labels: enhancement

#36 Add indices for modules
  main.py
Labels: enhancement

#35 Fix update notification
  requirements.txt
  requirements.windows.txt
  version.py
Labels: bug

#37 Beautify code
  config.py
  download_file.py
  download_file_ex.py
  main.py
  utils.py
  version.py
Labels: enhancement

#38 [doc] add new contributor
  README.md
  README_zh-hans.md
Labels: documentation

#44 [doc] fix typo of "ignored course"
  config.example.toml
  config.example.zh-hans.toml
  config.py
  main.py
Labels: bug, documentation

#49 New welcome message
  config.py
  download_file.py
  main.py
Labels: enhancement

#50 Add override organization mode
  config.example.toml
  config.example.zh-hans.toml
  config.py
  download_file.py
  download_file_ex.py
  main.py
Labels: enhancement

#51 Fix duplicate file
  README.md
  README_zh-hans.md
  main.py
Labels: bug

#52 [code] try reduce package size by removing tk
  .github/workflows/release.yml
  README.md
  README_zh-hans.md
  download_file_ex.py
  main.py
  patch_spec.py
  version.py
Labels: enhancement

#53 Module with file mode
  config.example.toml
  config.example.zh-hans.toml
  main.py
Labels: enhancement

#54 Remove stale file
  config.py
  main.py
  version.py
Labels: enhancement

#56 [doc] add scan stale file to config
  config.example.toml
  config.example.zh-hans.toml
  config.py
  main.py
Labels: documentation

#57 better support for updated files
  config.py
  main.py
Labels: bug

#59 [code] fix download bar appearing in wrong position
  download_file.py
Labels: enhancement

#60 [code] add support for removing empty directories
  main.py
  utils.py
Labels: enhancement
